### ISSUE TITLE
Allow `resources` to be specified as a string

### ISSUE THREAD

**Issue by Lnk2past** [Lnk2past/contest#17]
When specifying a resource to copy to the test folder, one must specify the `src` and `dst`, even if the name is going to be preserved. A resource should be allowed to be specified as a string, and `contest` should figure out the `src` and `dst` from that. i.e. allow:

```yaml
# see https://github.com/Lnk2past/contest
executable: ./bin/main.exe
test-cases:
    - name: test-01
      resources:
        - data
```
